root: true
env:
  browser: true
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint/eslint-plugin' # npm
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  indent: [off, 4]
  quotes: [warn, single, { allowTemplateLiterals: true }]
  prefer-const: [off]
  no-empty: [off]
  '@typescript-eslint/no-inferrable-types': [off]
  '@typescript-eslint/no-var-requires': [off]
  '@typescript-eslint/no-explicit-any': [off]
overrides:
  - files:
      - 'test/*.js'
    rules:
      '@typescript-eslint/no-var-requires': [off]
